// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Script-Teste', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Script-Teste', async function() {
    await driver.get("https://tailspin-space-game-web-test-15620.azurewebsites.net/")
    await driver.manage().window().setRect(1382, 722)
    await driver.findElement(By.css(".pagination > li:nth-child(4) > a")).click()
    await driver.findElement(By.id("profile-24")).click()
    await driver.findElement(By.css("#profile-modal-24 h1")).click()
    await driver.wait(until.elementIsVisible(await driver.findElement(By.css("#profile-modal-24 h1"))), 5000)
    {
      const elements = await driver.findElements(By.css("#profile-modal-24 h1"))
      assert(elements.length)
    }
    await driver.findElement(By.css("#profile-modal-24 .close")).click()
  })
})
